name: Build and Deploy Website

on:
    push:
        branches:
            - website-source-code

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout source branch
              uses: actions/checkout@v4
              with:
                  ref: website-source-code
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Nuke Previous Build
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git checkout n0ctos-website
                  git reset --hard
                  git clean -fdx

            - name: Deploy dist to n0ctos-website branch
              run: |
                  if [ ! -d "dist" ]; then
                    echo "‚ùå dist folder not found. Build failed."
                    exit 1
                  fi

                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git checkout website-source-code

                  cp -r dist/* .

                  git add .
                  git commit -m "Deploy from website-source-code @ $GITHUB_SHA"
                  git push origin n0ctos-website --force
