name: Build and Deploy Website

on:
    push:
        branches:
            - website-source-code

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout Previous build branch
              uses: actions/checkout@v5
              with:
                  ref: n0ctos-website
                  fetch-depth: 0
            - name: Nuke Previous Build
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git checkout n0ctos-website
                  git reset --hard
                  git clean -fdx

            - name: Checkout source branch
              uses: actions/checkout@v5
              with:
                  ref: website-source-code
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Deploy dist to n0ctos-website branch
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git checkout website-source-code
                  
                  npm run build
                  ls
                  
                  if [ ! -d "dist" ]; then
                    echo "‚ùå dist folder not found. Build failed."
                    exit 1
                  fi
                  
                  git add /dist/
                  git commit -m "Deploy from website-source-code @ $GITHUB_SHA"
                  git push origin n0ctos-website --force
                  
            - name: Unpack the deplyed /dist to root
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git checkout n0ctos-website
                  cp -r /dist/* /
                  rm -r /dist
